server:
  port: 8091

spring:
  application:
    name: recycle-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#   url: jdbc:mysql://localhost:3306/recycle_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    url: jdbc:mysql://47.108.83.101:3306/recycle_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: tama1998
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: recycle_admin_secret_key_2024_at_least_32_bytes_long
  expiration: 604800000

aliyun:
  sms:
    access-key-id: your-access-key-id
    access-key-secret: your-access-key-secret
    sign-name: 上会回收
    template-code: SMS_000000000
